services:
    catalog.handler.create_order:
        class: Backend\Modules\Catalog\Domain\Order\Command\CreateOrderHandler
        arguments:
            - "@catalog.repository.order"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Order\Command\CreateOrder }

    catalog.handler.update_order:
        class: Backend\Modules\Catalog\Domain\Order\Command\UpdateOrderHandler
        arguments:
            - "@catalog.repository.order"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Order\Command\UpdateOrder }

    catalog.handler.delete_order:
        class: Backend\Modules\Catalog\Domain\Order\Command\DeleteOrderHandler
        arguments:
            - "@catalog.repository.order"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Order\Command\DeleteOrder }

    catalog.handler.create_order_address:
        class: Backend\Modules\Catalog\Domain\OrderAddress\Command\CreateOrderAddressHandler
        arguments:
            - "@catalog.repository.order_address"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderAddress\Command\CreateOrderAddress }

    catalog.handler.update_order_address:
        class: Backend\Modules\Catalog\Domain\OrderAddress\Command\UpdateOrderAddressHandler
        arguments:
            - "@catalog.repository.order_address"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderAddress\Command\UpdateOrderAddress }

    catalog.handler.delete_order_address:
        class: Backend\Modules\Catalog\Domain\OrderAddress\Command\DeleteOrderAddressHandler
        arguments:
            - "@catalog.repository.order_address"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderAddress\Command\DeleteOrderAddress }

    catalog.handler.create_order_product:
        class: Backend\Modules\Catalog\Domain\OrderProduct\Command\CreateOrderProductHandler
        arguments:
            - "@catalog.repository.order_product"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderProduct\Command\CreateOrderProduct }

    catalog.handler.update_order_product:
        class: Backend\Modules\Catalog\Domain\OrderProduct\Command\UpdateOrderProductHandler
        arguments:
            - "@catalog.repository.order_product"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderProduct\Command\UpdateOrderProduct }

    catalog.handler.delete_order_product:
        class: Backend\Modules\Catalog\Domain\OrderProduct\Command\DeleteOrderProductHandler
        arguments:
            - "@catalog.repository.order_product"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderProduct\Command\DeleteOrderProduct }

    catalog.handler.create_order_vat:
        class: Backend\Modules\Catalog\Domain\OrderVat\Command\CreateOrderVatHandler
        arguments:
            - "@catalog.repository.order_vat"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderVat\Command\CreateOrderVat }

    catalog.handler.update_order_vat:
        class: Backend\Modules\Catalog\Domain\OrderVat\Command\UpdateOrderVatHandler
        arguments:
            - "@catalog.repository.order_vat"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderVat\Command\UpdateOrderVat }

    catalog.handler.delete_order_vat:
        class: Backend\Modules\Catalog\Domain\OrderVat\Command\DeleteOrderVatHandler
        arguments:
            - "@catalog.repository.order_vat"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderVat\Command\DeleteOrderVat }

    catalog.handler.create_order_status:
        class: Backend\Modules\Catalog\Domain\OrderStatus\Command\CreateOrderStatusHandler
        arguments:
            - "@catalog.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderStatus\Command\CreateOrderStatus }

    catalog.handler.update_order_status:
        class: Backend\Modules\Catalog\Domain\OrderStatus\Command\UpdateOrderStatusHandler
        arguments:
            - "@catalog.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderStatus\Command\UpdateOrderStatus }

    catalog.handler.delete_order_status:
        class: Backend\Modules\Catalog\Domain\OrderStatus\Command\DeleteOrderStatusHandler
        arguments:
            - "@catalog.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderStatus\Command\DeleteOrderStatus }
